# Module 5 S1 - Numpy & Arrays

In [8]:
import numpy as np

In [10]:
x = np.array([2,4,6])
print (x)


[2 4 6]


In [11]:
x = np.array([[2,4,6],[2,4,6]])
print (x)

[[2 4 6]
 [2 4 6]]


In [15]:
data = np.array([[1,2,3],[4,5,6]])
data

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
np.arange(7)


array([0, 1, 2, 3, 4, 5, 6])

In [18]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [21]:
data = np.array([1,2,3,4,5,6,7,8])
data

array([1, 2, 3, 4, 5, 6, 7, 8])

In [22]:
data[1]

np.int64(2)

In [23]:
data[-1]

np.int64(8)

In [24]:
data[1:]

array([2, 3, 4, 5, 6, 7, 8])

In [26]:
data = np.array([[1,2,3],[4,5,6]])
data

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
data[0,:]

array([1, 2, 3])

In [29]:
data[:,-1]

array([3, 6])

In [27]:
data[:,[0,2]]

array([[1, 3],
       [4, 6]])

In [31]:
data[0,1] = 7
data

array([[1, 7, 3],
       [4, 5, 6]])

In [33]:
data[1,:] = 8
data

array([[1, 7, 3],
       [8, 8, 8]])

In [34]:
data[0,:2] = [9,10]
data

array([[ 9, 10,  3],
       [ 8,  8,  8]])

In [ ]:
data[1,[0,2]] = [9,10]
data            

array([[ 9, 10,  3],
       [ 9,  8, 10]])

In [41]:
data1 = np.array([8.25, 3.26, 5.64])

In [42]:
data1 - 10

array([-1.75, -6.74, -4.36])

In [43]:
data1 * 2

array([16.5 ,  6.52, 11.28])

In [44]:
data1

array([8.25, 3.26, 5.64])

In [45]:
data1 / 2


array([4.125, 1.63 , 2.82 ])

In [46]:
data = np.array([[1,2,3],[4,5,6]])
data

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
data2 = np.array([[7,8,9],[10,11,7]])
data2

array([[ 7,  8,  9],
       [10, 11,  7]])

In [48]:
data * data2

array([[ 7, 16, 27],
       [40, 55, 42]])

In [49]:
data + data1

array([[ 9.25,  5.26,  8.64],
       [12.25,  8.26, 11.64]])

In [50]:
data2 = np.array([[7,8,9],[10,11,7]])
data2

array([[ 7,  8,  9],
       [10, 11,  7]])

In [52]:
data2 > 8

array([[False, False,  True],
       [ True,  True, False]])

In [53]:
data

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
data > data2

array([[False, False, False],
       [False, False, False]])

In [55]:
data2

array([[ 7,  8,  9],
       [10, 11,  7]])

In [56]:
np.sqrt(data2)

array([[2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 2.64575131]])

In [57]:
np.round(np.sqrt(data2),2)

array([[2.65, 2.83, 3.  ],
       [3.16, 3.32, 2.65]])

In [58]:
data2

array([[ 7,  8,  9],
       [10, 11,  7]])

In [59]:
np.maximum(data, data2)

array([[ 7,  8,  9],
       [10, 11,  7]])

In [60]:
data2.min()

np.int64(7)

In [61]:
data2.sum()

np.int64(52)

In [62]:
data2.mean()

np.float64(8.666666666666666)

In [66]:
data3 = np.array([2,6,4,5,10])
data3

array([ 2,  6,  4,  5, 10])

In [67]:
np.sort(data3)

array([ 2,  4,  5,  6, 10])

In [68]:
data = np.array([6,5,3,4,6,5])
data

array([6, 5, 3, 4, 6, 5])

In [71]:
data.sort()
data

array([3, 4, 5, 5, 6, 6])

In [72]:
data4 = np.array([1,4,2,7,6])
data4

array([1, 4, 2, 7, 6])

In [73]:
data3

array([ 2,  6,  4,  5, 10])

In [74]:
data4[data4 > 3]

array([4, 7, 6])

In [75]:
data4 [ data3 > 3 ] = 0
data4

array([1, 0, 0, 0, 0])