# Practice 1: numpy Arrays

In [1]:
import numpy as np

In [2]:
x = np.ones((3,4))

In [3]:
print("Shape of x:", x.shape)

Shape of x: (3, 4)


In [8]:
np.resize(x, (6,4))
x = np.resize(x, (6, 4))

In [9]:
print("Array before transposing: \n", x)
print("Shape of x array before transposing:", x.shape)

Array before transposing: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Shape of x array before transposing: (6, 4)


In [11]:
x = x.T

In [14]:
print("Array after transposing: \n", x)
print("Shape of array before transposing:", x.shape)

Array after transposing: 
 [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
Shape of array before transposing: (4, 6)


# Practice 2: numpy Arrays

In [15]:
import numpy as np

In [16]:
my_2d_array = np.array([[1,2,3,4],[5,6,7,8]], dtype = np.int64)

In [18]:
print("my_2d_array before appending: \n", my_2d_array)

my_2d_array before appending: 
 [[1 2 3 4]
 [5 6 7 8]]


In [20]:
new_2d_array = np.append(my_2d_array, [[7],[8]], axis =1)

In [21]:
print("new_2d_array: \n", new_2d_array)

new_2d_array: 
 [[1 2 3 4 7]
 [5 6 7 8 8]]


In [22]:
print("my_2d_array after appending: \n", my_2d_array)

my_2d_array after appending: 
 [[1 2 3 4]
 [5 6 7 8]]


# Laboratory Activity

In [40]:
import numpy as np

def initialize_movies():
    movies = {
        "1": {"title": "Movie A: The Matrix", "seats": np.arange(1, 101).reshape(10, 10)},
        "2": {"title": "Movie B: Inception", "seats": np.arange(1, 101).reshape(10, 10)},
        "3": {"title": "Movie C: Interstellar", "seats": np.arange(1, 101).reshape(10, 10)}
    }
    return movies

def displaySeats(movie):
    print(f"\n--- {movie['title']} Seating ---")
    print("=" * 55)
    print("                       SCREEN                      ")
    print("=" * 55)
    
    seats = movie["seats"]
    for row in seats:
        for seat in row:
            if seat == 0:
                print(f"{'[X]':>4} ", end=" ") 
            else:
                print(f"{seat:4d} ", end=" ")
        print() 
    print("=" * 55)
    print("Legend: [X] = Reserved\n")

def ticketReservation(movies):
    print("\n--- Available Movies ---")
    for key, val in movies.items():
        print(f"[{key}] {val['title']}")
        
    m_choice = input("Select a movie (1-3): ")
    if m_choice in movies:
        displaySeats(movies[m_choice])
        try:
            seat_num = int(input("Enter seat number to reserve (1-100): "))
            if 1 <= seat_num <= 100:
                row = (seat_num - 1) // 10
                col = (seat_num - 1) % 10
                
                if movies[m_choice]["seats"][row][col] == 0:
                    print("\n[!] Sorry, that seat is already reserved.")
                else:
                    movies[m_choice]["seats"][row][col] = 0
                    print(f"\n[*] Success! Seat {seat_num} reserved for {movies[m_choice]['title']}.")
            else:
                print("\n[!] Invalid seat number.")
        except ValueError:
            print("\n[!] Please enter a valid number.")
    else:
        print("\n[!] Invalid movie selection.")

def cancelReservation(movies):
    print("\n--- Available Movies ---")
    for key, val in movies.items():
        print(f"[{key}] {val['title']}")
        
    m_choice = input("Select the movie for your reservation (1-3): ")
    if m_choice in movies:
        try:
            seat_num = int(input("Enter seat number to cancel (1-100): "))
            if 1 <= seat_num <= 100:
                row = (seat_num - 1) // 10
                col = (seat_num - 1) % 10
                
                if movies[m_choice]["seats"][row][col] == 0:
                    movies[m_choice]["seats"][row][col] = seat_num
                    print(f"\n[*] Success! Reservation for seat {seat_num} cancelled.")
                else:
                    print("\n[!] That seat is not currently reserved.")
            else:
                print("\n[!] Invalid seat number.")
        except ValueError:
            print("\n[!] Please enter a valid number.")
    else:
        print("\n[!] Invalid movie selection.")
movies = initialize_movies()

In [ ]:
while True:
    print("\n" + "*"*30)
    print("   MOVIE TICKET SYSTEM")
    print("*"*30)
    print("1. Display Seats")
    print("2. Reserve a Ticket")
    print("3. Cancel a Reservation")
    print("4. Exit")
    
    choice = input("Enter your choice (1-4): ")
    
    if choice == '1':
        print("\n--- Available Movies ---")
        for key, val in movies.items():
            print(f"[{key}] {val['title']}")
        m_choice = input("Select a movie to view (1-3): ")
        if m_choice in movies:
            displaySeats(movies[m_choice])
        else:
            print("\n[!] Invalid movie selection.")
            
    elif choice == '2':
        ticketReservation(movies)
        
    elif choice == '3':
        cancelReservation(movies)
        
    elif choice == '4':
        print("\nExiting system. Goodbye!")
        break
        
    else:
        print("\n[!] Invalid choice. Please select 1-4.")